// district 1

export const alicia = [
    "Antique St.",
    "Balayan",
    "Batangas St.",
    "Camarines St.",
    "Cotabato St.",
    "Davao St.",
    "F. Santiago St.",
    "Ilocos Norte St.",
    "Ilocos Sur",
    "Pangasinan",
];

export const bahaytoro = [
    "Aberdeen St.",
    "Accounting St.",
    "Actuarial St.",
    "Administration",
    "Agueda St.",
    "Alcoy St.",
    "Alley 14",
    "Alley 15",
    "Alley 2",
    "Agha Rd",
    "Apollo St.",
    "April St.",
    "Asset",
    "Astra Drive",
    "Balayan",
    "Batangas St.",
    "B.S Aquino St",
    "Bongavilla",
    "Cadena De Amor St",
    "Calla Lily St.",
    "Camarines St.",
    "Carmel Ave",
    "Carlos",
    "Cattleya",
    "Clarion Lily St.",
    "Clarion St.",
    "Congressional Ave.",
    "Cotabato St.",
    "C.Rd",
    "Dakilang Lumpo",
    "Davao St.",
    "Elliptical Rd",
    "Faith",
    "Faith St",
    "February St.",
    "Fema Rd",
    "F. Santiago St.",
    "Geronimo",
    "General Ave",
    "Gardenia Circle Rd",
    "Golden Acres Rd",
    "Hereford St.",
    "Hope St",
    "Ilocos Norte St.",
    "Ilocos Sur",
    "January St.",
    "Jaime St.",
    "Jersey St.",
    "Jupiter St.",
    "Pangasinan",
    "Pangilinan Dr",
    "Palawan St.",
    "Parinas Street",
    "Personnel",
    "Pluto St.",
    "Pugad Lawin St",
    "Rd A",
    "Rd B",
    "Rd C",
    "Rd 14",
    "Rd 15",
    "Rd 16",
    "Rd 18",
    "Rd 19",
    "Rd 20",
    "Rd 21",
    "Rd 22",
    "Rd 23",
    "Ricardo St",
    "Records Ext",
    "Ricarte",
    "Rosario",
    "Sagittarius St",
    "Sanggumay",
    "Santiago Ave.",
    "SB Rd",
    "Seminary Rd",
    "September St",
    "Shorthorn St.",
    "Sitio Militar",
    "Sinagtala St.",
    "Sola Dr",
    "Sto. Domingo",
    "Stella",
    "St. Jude Rd",
    "St. Gertrudes",
    "Terra Drive",
    "Tulip Lane",
    "Uranus St.",
    "Venus St.",
    "Vertis Dr",
    "Villa Socorro St.",
    "Virginia St.",
    "Visayas Ave.",
    "Wisdom St.",
]

export const balingasa = [
    "Acacia St.",
    "Amethyst St.",
    "Andrade St.",
    "Apacible St.",
    "Atis St.",
    "Balingasa Rd",
    "Balingasa St.",
    "Balintawak",
    "Bignay St.",
    "Cloverleaf Drive",
    "Diamond St",
    "Eleven Rd",
    "Emerald St.",
    "Harmony St.",
    "Hope St.",
    "J. Aquino St.",
    "Joy St.",
    "Langka St",
    "Lily St.",
    "Maximo Viola St",
    "Narra Alley",
    "Old Samson Rd",
    "Onyx St",
    "Pearl St.",
    "Picarra St.",
    "Santo Cristo",
    "Santo Domingo Avenue",
    "Valentin Ventura St.",
    "Villanueva Compound",
];

export const bungad = [
    "Aguilar St.",
    "Baler St.",
    "Balec St.",
    "Bayan St.",
    "Bayaya St.",
    "Bulacan St.",
    "Esquivel St.",
    "Fulgencio St.",
    "Laguna St.",
    "Lilibeth St.",
    "Luna St.",
    "M.H Del Pilat St.",
    "Miller St.",
    "Moore St.",
    "Morquecillo St.",
    "Rest Haven St.",
    "Robina St.",
    "Sanchez St.",
    "Samuel St.",
    "Supnet St.",
    "Victoria St.",
    "Villegas St.",
]

export const damar = [
    "Dadiangas St.",
    "Daet St.",
    "Damar Loop",
    "Dampol St.",
    "Damortis St.",
    "Dancalan St.",
    "Dasmarinas St.",
    "Daraga St.",
    "Dayne St.",
    "Dinalupihan St.",
    "Donsol St.",
]

export const damayan = [
    "Alhambra St.",
    "Basinillo St.",
    "Caragay St.",
    "Flores De Mayo St.",
    "G. Felipe Sc. Avenue",
    "H. Francisco St.",
    "Morato St.",
    "P. Santillan St.",
    "Pabillare St.",
    "San Joaquin St.",
    "San Jose St.",
    "San Pedro Baustista Road",
    "San Vicente St.",
    "Santos St.",
    "Subic St.",
    "Tolentino St.",
    "Umali St.",
    "West Riverside Road",
    "Wilson St.",
    "Zamora St.",
];


export const delmonte = [
    "Apollo St.",
    "Canseco",
    "Ernesto Porto St.",
    "Fernando Poe Jr. Avenue",
    "Florencia St.",
    "General Wood St.",
    "Judge Juan Luna St.",
    "Lincoln St.",
    "M. Razo St.",
    "Manalo St.",
    "Marinduque St.",
    "Navarette St.",
    "Osmena St.",
    "Pitimini St.",
    "San Antonio St.",
    "San Pedro St.",
    "Santiago St.",
    "Tolentino St.",
    "Valencia St.",
    "West Valencia Drive",
];


export const katipunan = [
    "Esmeraldo Beltran Street",
    "Mangga Street",
    "Montenegro Street",
    "Ricardo Street",
]

export const mariblo = [
    "Bernardo Street",
    "Dagupan Street",
    "De Vera Street",
    "Mapalad Street",
    "Montemayor Street",
    "Pongco Street",
    "Umali Street",
]

export const masambong = [
    "Amaloi Street",
    "Amuslan Street",
    "Bahawan Street",
    "Bakil Street",
    "Cadang Street",
    "Cagna Street",
    "Capoas Street",
    "Corumi Street",
    "Gabo Street",
    "Gasan Street",
    "Ilihan Street",
    "Inaman Street",
    "Mabituan Street",
    "Malac Street",
    "Malasimbo Street",
    "Masola Street",
    "Monong Street",
    "Posooy Street",
    "Payte Street",
    "Tuktukan Street",
    "Tinaduan Street",
    "Wayan Alley",
    "Wayan Street",
]

export const amoranto = [
    "Angelo Street",
    "Apo Street",
    "Binuang Street",
    "General Tinio Street",
    "Ipo Street",
    "Lunas Street",
    "Magnas Street",
    "Malaya Street",
    "Malindang Street",
    "Mayo Street",
    "Mayon Street",
    "Santa Catalina Street",
    "Scout Alcaras Street",
    "Wakat Street",
]

export const nayongkanluran = [
    "Masbate Street",
    "Sorsogon Street",
    "Sulu Street",
    "Surigao Street",
    "Zamboanga Street",
]

export const paangbundok = [
    "Abao Street",
    "Angelo Street",
    "Bulusan Street",
    "Calavite Street",
    "Dr.Alejos Street",
    "Iba Street",
    "Iriga Street",
    "Isarog Street",
    "Labo Street",
    "Mariveles Street",
]

export const pagibigsanayon = [
    "Banal Street",
    "Dona Carmen Street",
    "Don Ramon Street",
    "E.Tomas Street",
    "F.Torres Street",
    "Fadri Alley Street",
    "Fadri Compound",
    "Fernandez Street",
    "J.Pineda Street",
    "Ligaya Street",
    "P.Gonzales Alley",
    "P.Gonzales Street",
]

export const paltok = [
    "Anak Bayan Street",
    "Araw Street",
    "Aragon Street",
    "Basa Street",
    "Capiz Street",
    "Catanduanes Street",
    "General H.De Pilar Street",
    "Gomez Street",
    "Guevarra Street",
    "Hernandez Street",
    "Kalawag Street",
    "Kundiman Street",
    "Matias Street",
    "Mendoza Street",
    "Natividad Street",
    "Santiago Street",
    "V.Ilagan Street",
    "Zamora Street",
    "Zorra Street",
]

export const paraiso = [
    "Benitez St.",
    "Bodino St.",
    "Cooper St.",
    "Devera St.",
    "F.Bautista St.",
    "Gordon St.",
    "M. Rivera St.",
    "San Joaquin St.",
]

export const philam = [
    "Baguito Rd",
    "Cabanatuan",
    "Dansalan Rd",
    "East Lawin",
    "East Maya Dr",
    "Legaspi Rd",
    "Lipa Rd",
    "North Lawin Ave",
    "San Pablo Road",
    "South Lawin",
    "South Maya Dr",
    "Vigan",
    "West Ave",
    "West Lawin",
    "West Maya Dr",
]

export const project6 = [
    "A 14",
    "A 15",
    "A 16",
    "A 23",
    "A 24",
    "A 25",
    "A 26",
    "A 27",
    "A 28",
    "A 29",
    "A 30",
    "A 31",
    "A 32",
    "A 33",
    "A 34",
    "A 6",
    "A 8",
    "A 8A",
    "Alley 1",
    "Alley 15",
    "Alley 17",
    "Alley 18",
    "Alley 2",
    "Alley 3",
    "Alley 4",
    "Alley 7",
    "Mindanao Avenue",
    "North Ave",
    "Palawan Street",
    "Rd 1",
    "Rd 10",
    "Rd 11",
    "Rd 13",
    "Rd 16",
    "Rd 2",
    "Rd 3",
    "Rd 4",
    "Rd 5",
    "Rd 5-A",
    "Rd 6",
    "Rd 7",
    "Rd 8",
    "Rd 9",
];

export const ramonmagsaysay = [
    "Abra St.",
    "Antique St.",
    "Bukidnon St.",
    "Cagayan St.",
    "Cotabato St.",
    "Ilocos Norte St.",
    "Ilocos Sur St.",
    "Isabela St.",
    "Laguna St.",
    "Sto Nino St.",
]

export const saintpeter = [
    "Linaw St.",
    "Malaya St.",
    "Matutum St.",
    "Palanan St.",
    "Pao St.",
    "Patok St.",
    "Santa Catalina St.",
    "Scout Alcaraz St.",
    "Sibuyan St.",
    "Sicaba St.",
]

export const salvacion = [
    "Agusan St.",
    "Baco St.",
    "Cadig St.",
    "Calavite St.",
    "Dr. Alejos St.",
    "Halcon 1 St.",
    "Hernani St.",
    "Iba St.",
    "Ipo St.",
    "Iriga St.",
    "Isarog St.",
    "Mariveles St.",
    "Sampaguita St.",
]

export const sanantonio = [
    "Adams St.",
    "Batangas St.",
    "Capillan St.",
    "Domingo St.",
    "Guerrero St.",
    "Lincoln St.",
    "Lopez St.",
    "M.H DEl Pillar St.",
    "Montenegro St.",
    "P.Garcia St.",
    "Piopongco St.",
    "R.Fernandez St.",
    "San Antonio St.",
    "San Jose St.",
    "Santa Fe St.",
    "Santiago St.",
    "Santo Nino St.",
    "Tolentino St.",
    "Umandal St.",
]

export const sanisidro = [
    "19 De Agosto",
    "Bagong Buhay",
    "Batanes St",
    "Bayani",
    "Bustamante",
    "Cordilera",
    "Cuatro De Julio",
    "G.Tuazon",
    "Liberation",
    "Luisito",
    "Mata ng Nayon",
    "Nicanor Ramirez",
    "Premero De Mayo St",
    "Romblon St",
    "San Isidro St",
    "Sobriedad",
    "Unang Hakbang",
    "Union Civica",
    "Visayas Ave",
    "Womens Club",
]

export const sanjose = [
    "Dome St.",
    "Tangali St.",
    "Tinagan St.",
    "Mauban St.",
    "G. Roxas St.",

]

export const westtriangle = [
    "Bayanihan Street",
    "Tomas Benitez Street",
    "Bulletin Street",
    "Chronicle Street",
    "Daily Mirror Street",
    "Examiner Street",
    "Evening News Street",
    "Free Press Street",
    "Kayumanggi Street",
    "Ligaya Street",
    "Liwayway Street",
    "Marikit Street",
    "Quezon Avenue",
    "Times Street",
    "West 4th Street",
    "West 6th Street",
]

export const veteransvillage = [
    "Alley 1",
    "Alley 2",
    "Alibangbang",
    "Anahaw Street",
    "Aramismis Street",
    "Bakawan Street",
    "Bansalangin Street",
    "Block 17 Street",
    "Calumpang Street",
    "Calumpit Street",
    "Dangay Street",
    "Danupra Street",
    "Duhat",
    "Esteban Street",
    "Jupiter Street",
    "Kalayaan Alley",
    "Kalayaan Street",
    "Kalamansanay Avenue",
    "Kalyos Street",
    "Lanete Street",
    "Lanutan Alley",
    "Lanutan Street",
    "Lucerio R.Kasilag Street",
    "Magatpat Street",
    "Malunggay Street",
    "Mangachapoy Street",
    "Muñoz Market",
    "Narig Street",
    "Pagatpat Street",
    "Pahutan Street",
    "Palomaria Street",
    "Payne Street",
    "Poe Jr.Avenue",
    "Road A",
    "Road B",
    "Sagrada Familia Street",
    "Saleng Street",
    "Santol Alley",
    "Siete A Street",
    "Siete B Street",
    "Tanguile Street",
]

export const vasra = [
    "DANR Street",
    "DENR Road",
    "Fisheries Street",
    "Forestry Street",
    "Forestry Street Extension",
    "Lands Street",
    "MGB Road",
    "Mines Street",
    "Palanas Alley",
    "Road 10",
    "Visayas Avenue",
]

export const talayan = [
    "Calamba Street",
    "Caraballo Street",
    "Catmon Street",
    "Don Ramon Street",
    "Gregorio Araneta Avenue",
    "Malambo Street",
    "Manikling Street",
    "Maria Clara Street",
    "Pasian Street",
    "Sabrang Street",
    "Silay Street",
    "Tapi Street",
    "Talayan Road",
]

export const sienna = [
    "Banawe Street",
    "Biak na Bato Street",
    "Bingo Street",
    "Cetacio Street",
    "Cresta Street",
    "Don Jose Street",
    "Malinao Street",
    "Palali Street",
    "Santa Catalina Street",
    "Scout Alcaraz Street",
    "Tabayoc Street",
    "Ubay Street"
];

export const santodomingo = [
    "AIB Sagada Street",
    "Atok Street",
    "Banawe Street",
    "Biak na Bato Street",
    "Calamba Street",
    "Dapitan Street",
    "Don Jose Street",
    "Don Manuel Agregado Avenue",
    "Don Pepe Street",
    "Mariano J.Cuenco Street",
    "Maria Clara Street",
    "Macopa Street",
    "N.S.Amoranto Sr.Avenue",
    "Nicanor Roxas Street",
    "P.Florentino Street",
    "Samat Street",
    "Santo Domingo Avenue",
    "Simoun Street",
    "Tirad Pass Street",
]

export const santocristo = [
    "Balayan Street",
    "Capiz Street",
    "Fort Santiago Street",
    "Ilocos Sur Street",
    "Iloilo Street",
    "Lanao Street",
    "Misamis Street",
    "Nueva Ecija Extension",
    "Nueva Vizcaya Street",
    "Pampanga Street",
    "Pangasinan Street",
    "Romblon Street",
    "Samar Street",
    "South Road",
]

export const santateresita = [
    "Apo Street",
    "Baco Street",
    "Dr.Alejos Street",
    "Dapitan Street",
    "Halcon 1 Street",
    "Halcon 2 Street",
    "Iba Street",
    "Iriga Street",
    "Isarog Street",
    "Kanlaon Street",
    "Mariveles Street",
    "Mayon Street",
    "Nicanor Roxas Street",
    "P.Florentino Street",
    "Quezon Avenue",
]

export const santacruz = [
    "Captain Paredes",
    "Colonel Martelino Street",
    "Colonel Martirez Street",
    "Colonel Moran Street",
    "Colonel Osamiz Street",
    "Fernando Poe Jr.Street",
    "General de Jesus Street",
    "General Lim Street",
    "General Segunda Street",
    "Jose Abad Santos Street",
    "Quezon Avenue",
    "Vinzon Street",
]