export const bagongsilangan = [
    "A. Bonifacio Extension",
    "A. Bonifacio Street",
    "Abraham Lane",
    "Administrative Road",
    "Aklan(tertiary)",
    "Alpine Street",
    "Anahaw Street",
    "Apple Street",
    "Arayat Street",
    "Aster Street",
    "Atlas Street",
    "Azucadores Street",
    "Azucarera Street",
    "Bach Street",
    "Bagasse Street",
    "Bagon Street",
    "Banaba Street",
    "Bangkal Street",
    "Basi Street",
    "Batasan Complex Road(service)",
    "Battalion Street",
    "Besang Pass Street",
    "Bicameral Road",
    "Blessing Street",
    "Blue Bird Street",
    "Briza Street",
    "Broadbill Road",
    "Byron Street",
    "Caimito Street",
    "Camachile Street",
    "Canefield Street",
    "Canonical Road",
    "Cedar Street",
    "Cherry Street",
    "Clover Street",
    "Constitutional Road",
    "Corregidor Street",
    "Cypress Street",
    "Daffodil Street",
    "Dakila Interior",
    "Dakila Street",
    "Daniel Street",
    "Davao Street",
    "David Street",
    "Dinorado Street",
    "Diwata Street",
    "Doña Juliana Street",
    "Don Vicente Street",
    "Dona Juliana Street",
    "Dove Street",
    "Eagle Extension",
    "Eagle Street",
    "Empire Hilltop",
    "Empire Road",
    "Exekiel Street",
    "Ezra Street",
    "Faisal Street",
    "Faithful Street",
    "Falconet Street",
    "Fantail Street",
    "Federal Road",
    "Fern Street",
    "Filheights Avenue",
    "Flower Pickle Street",
    "Fonda Street",
    "Fox Street",
    "Frost Street",
    "Gandhi Street",
    "Gardenia Street",
    "Gemilina Street",
    "General Aguinaldo Street",
    "General Alejandrino Street",
    "General Canon Street",
    "General M.H. del Pilar Extension",
    "General M.H. del Pilar Street",
    "General Mascardo Street",
    "Glenn Street",
    "Golden Shower Street",
    "Graceful Street",
    "Grant Street",
    "Hacienda Street",
    "Haciendero Street",
    "Hailey Street",
    "Hanna Street",
    "Hart Street",
    "Hawk Street",
    "Helpful Street",
    "Heron Street",
    "Hilton Street",
    "Holy Trinity Street",
    "Homer Street",
    "Hopeful Street",
    "Hornbill Street",
    "Hosea Street",
    "Humedo Street",
    "Hunt Street",
    "IBP Road(secondary)",
    "Ibsen Street",
    "Ilon-Ilon Street",
    "Inca Street",
];

export const batasanhills = [
    "A. Bonifacio",
    "Acacia",
    "Acacia St",
    "Adams",
    "Adler",
    "Afulgencia Dr",
    "Agate",
    "Albany",
    "Almaciga",
    "Almaciga St",
    "Alton St",
    "Amber",
    "Amethyst",
    "Amity Street",
    "Amsterdam St",
    "Angela",
    "Antique St",
    "Antonio Dr",
    "Aphrodite Dr",
    "Apitong St",
    "Apollo",
    "Apollo Dr",
    "Aquamarine",
    "Aramis",
    "Ariane",
    "Arne",
    "Artemis St",
    "Artemis St",
    "Athena Dr",
    "Athena St",
    "Atis",
    "Avery",
    "Bach",
    "Baker",
    "Baltimore St",
    "Banaba",
    "Barcelona",
    "Batasan Hills",
    "Batasan Rd",
    "Batasan-San Mateo Rd",
    "Battalion St",
    "Belfast St",
    "Belgrade St",
    "Bell",
    "Bills St",
    "Blake",
    "Boston St",
    "Brandford",
    "Brisbane St",
    "Bronze",
    "Budapest St",
    "Bunda Dr",
    "Byron",
    "C. Jocson St",
    "Cadmium",
    "Caimito",
    "Calantas",
    "Calle Luz",
    "Calle Victoria",
    "Cambridge St",
    "Cape Town St",
    "Caracas St",
    "Carnelian Street",
    "Cash",
    "Catbalogan St",
    "Channel",
    "Chase",
    "Chico",
    "Chrysolite",
    "Cider",
    "Citrine",
    "Cohen",
    "Comet",
    "Commowealth Ave",
    "Congressional Rd",
    "Copenhagen St",
    "Copper",
    "Cotabato St",
    "Courage St",
    "Crane",
    "Curil",
    "Curtis",
    "Dakila St",
    "Dall",
    "Dalton",
    "Dao",
    "Darwin",
    "Davao Dr",
    "Defore",
    "Delhi St",
    "Denver",
    "Denver Loop",
    "Detroit St",
    "Diamond",
    "Diego Silang",
    "Dignity St",
    "Digos St",
    "Dodge",
    "Dona Francesca",
    "Dona Juliana",
    "Dona Justina",
    "Drakkar",
    "Duhat",
    "Dumas",
    "E. Aguinaldo",
    "Earth",
    "Emerald",
    "Emerald Street",
    "Emilio Jacinto St",
    "Eucalyptus",
    "Faith St",
    "Filinvest 1 Rd",
    "Filinvest 2 Rd",
    "Flintlane",
    "Frost",
    "G. Del Pilar",
    "G. Silang",
    "Galaxy",
    "Garnet",
    "Gold",
    "Guijo",
    "Guijo St",
    "Gumamela St",
    "Havana St",
    "Hawaii St",
    "Hercules Rd",
    "Hercules St",
    "Hills Street",
    "Honesty St",
    "Ilang-Ilang",
    "Interin Batasang Pambansa Rd",
    "Ipil",
    "J. Abad Santos",
    "J. Luna",
    "J. P. Rizal",
    "Jade",
    "Jade Street",
    "Jasmin",
    "Jasper",
    "Jupiter",
    "Kabihasnan St",
    "Kagandahan",
    "Kagawad Rd",
    "Kalayaan A",
    "Kalayaan B",
    "Kalayaan C",
    "Kaligayahan St",
    "Kalinisan",
    "Kalusugan",
    "Kamagong",
    "Kamagong St",
    "Kasayahan St",
    "Kasipagan Street",
    "Katarungan",
    "Katipunan Ext",
    "Kaunlaran",
    "Kingston St",
    "Lakatan St",
    "Lanzones",
    "Lapu Lapui",
    "Latundan St",
    "Lisbon St",
    "Livelihood St",
    "Liverpool",
    "London",
    "Luzon",
    "Mabolo",
    "Macopa",
    "Madrid St",
    "Mount Rindjani St",
    "Mount Rushmore St",
    "Mount Sajama",
    "Mount Sanford",
    "Mount Semeru",
    "Mount Shasta",
    "Mount Vancouver St",
    "Mount Vernon",
    "Mount Whitney St",
    "Mount Willamson St",
    "Mt. Hubbard",
    "Mt. Rainier St",
    "Narra",
    "Narra St",
    "Neptune",
    "Neptune St",
    "New Castle St",
    "Nickel",
    "Nike Dr",
    "Onyx",
    "Opal",
    "Oxwich",
    "Panama St",
    "Pangasinan St",
    "Paris St",
    "Pearl",
    "Pembroke",
    "Pepita St",
    "Platinum",
    "Plymouth St",
    "Pontevedra",
    "Presidential Rd",
    "Queensland St",
    "Raglan",
    "Rolling Lane",
    "Rome St",
    "Rosal St",
    "Rose St",
    "Rossas St",
    "Rowena St",
    "Ruby",
    "Saba St",
    "Saging St",
    "Saigon St",
    "Sampaguita",
    "San Gabriel",
    "Santan St",
    "Santo Nino St",
    "Sapphire",
    "Sapphire St",
    "Saret St",
    "Seattle St",
    "Senatorial Rd",
    "Senorita Street",
    "Session Rd",
    "Singatala St",
    "Southend",
    "Stockholm St",
    "Sunflower",
    "Sunnyside Dr",
    "Sydney St",
    "Tanguile",
    "Tarlac St",
    "Tarnate St",
    "Tatiana",
    "Tokyo",
    "Topaz",
    "Turquise",
    "Venus Dr",
    "Venus St",
    "Vienna",
    "Vista Real Ave",
    "Washington St",
    "Wellington St",
    "Woodstock St",
    "Yakal",
    "Yakal St",
    "Zambales St",
    "Zeus Dr",
    "Zeus St",
];

export const commonwealth = [
    "A. Bonifacio",
    "Abelardo",
    "Adarna ST",
    "Aguinaldo",
    "Apple St",
    "Bacer St",
    "Bach",
    "Batasan Rd",
    "Bato-Bato St",
    "Beethoven",
    "Bicoleyte",
    "Brahms",
    "Caridad",
    "Chopin",
    "Commonwealth Ave",
    "Cuenco St",
    "D. Carmencita",
    "Dear St",
    "Debussy",
    "Don Benedicto",
    "Don Desiderio Ave",
    "Don Espejo Ave",
    "Don Fabian",
    "Don Jose Ave",
    "Don Macario",
    "Dona Adaucto",
    "Dona Agnes",
    "Dona Ana Candelaria",
    "Dona Carmen Ave",
    "Dona Cynthia",
    "Dona Fabian Castillo",
    "Dona Juliana",
    "Dona Lucia",
    "Dona Maria",
    "Dona Severino",
    "Ecol St",
    "Elliptical Rd",
    "Elma St",
    "Ernestine",
    "Ernestito",
    "Eulogio St",
    "Freedom Park",
    "Gen. Evangelista",
    "Gen. Ricarte",
    "Geraldine St",
    "Gold St",
    "Grapes St",
    "Handel",
    "Hon. B. Soliven",
    "Jasmin St",
    "Johan St",
    "John Street",
    "Julius",
    "June June",
    "Kalapati St",
    "Kamagong St",
    "Kasoy St",
    "Kasunduan",
    "Katibayan St",
    "Katipunan St",
    "Katuparan",
    "Kaunlaran",
    "Kilyawan St",
    "La Mesa Drive",
    "Laurel St",
    "Lawin St",
    "Liszt",
    "Lunas St",
    "Ma Theresa",
    "Mango",
    "Manila Gravel Pit Rd",
    "Mark Street",
    "Markos Rd",
    "Martan St",
    "Martirez St",
    "Matthew St",
    "Melon",
    "Mozart",
    "Obanc St",
    "Ocampo Ave",
    "Odigal",
    "Pacamara St",
    "Pantaleona",
    "Paul St",
    "Payatas Rd",
    "Perez St",
    "Pilot Drive",
    "Pineapple St",
    "Pres. Osmena",
    "Pres. Quezon",
    "Pres. Roxas",
    "Pugo St",
    "Republic Ave",
    "Riverside Ext",
    "Riverside St",
    "Rose St",
    "Rossini",
    "Saint Anthony Street",
    "Saint Paul Street",
    "San Andres St",
    "San Diego St",
    "San Miguel St",
    "San Pascual",
    "San Pedro",
    "Sanchez St",
    "Santo Nino Street",
    "Santo Rosario Street",
    "Schubert",
    "Simon St",
    "Skinita Shortcut",
    "Steve St",
    "Sto. Nino",
    "Strauss",
    "Sumapi Drive",
    "Tabigo St",
    "Thomas St",
    "Verdi",
    "Villonco",
    "Wagner",
];

export const holyspirit = [
    "A. Bonifacio",
    "A. Labrador",
    "A. Luna",
    "Adelfa",
    "AFP Rd",
    "Alley 2",
    "Amethyst Street",
    "Antonio Barreon",
    "Army Rd",
    "Artesia",
    "Artillery Rd",
    "Aurora",
    "B. F. Homes Rd",
    "Besang Pass Rd",
    "Calle Siete",
    "Capas Rd",
    "Cattleya",
    "Champaca",
    "Cherry Blosson",
    "Cirlo",
    "Commodore Rd",
    "Commonwealth Av",
    "Constabulary Rd",
    "Dahila",
    "Dalton Rd",
    "De Leon",
    "Don Armando",
    "Don Asterio",
    "Don Carlos",
    "Don Damaso",
    "Don Diosdado",
    "Don Doroteo",
    "Don Edilberto",
    "Don Elpidio Street",
    "Don Ernesto St",
    "Don Faustino",
    "Don Francisco",
    "Don Gregorio",
    "Don Jose Rd",
    "Don Juan",
    "Don Mario",
    "Don Matias",
    "Don Miguel",
    "Don Narciso",
    "Don Pedro",
    "Don Pio",
    "Don Primitivo",
    "Don Rafael",
    "Don Ramon",
    "Don Renato",
    "Don Romeo",
    "Don Senen",
    "Don Sergio",
    "Don Torribio",
    "Don Vicente",
    "Don Victorino",
    "Don Wilfredo",
    "Dona Felicidad",
    "Dona Isidora",
    "E. Ocampo",
    "Emerald St",
    "Everlasting",
    "F. Sotto",
    "F. Ventura",
    "Faustino",
    "Florentino Chioco",
    "Fort Santiago Rd",
    "General Rd",
    "Guerilla Rd",
    "Gumamela St",
    "H. Moncado",
    "Holy Spirit Drive",
    "Ilang-Ilang",
    "Ilang-Ilang St",
    "Immaculate Concepcion Street",
    "Infantry Rd",
    "J. Hontiveros St",
    "J. M. Aruego",
    "J. P. Rizal",
    "J. Paredes",
    "J. Romeo",
    "Jade St",
    "Jasmine",
    "Jasmine St",
    "Jose C. Locsin",
    "Jose M. Delgado",
    "Juan Ortega",
    "Kaunlaran",
    "Leyte Gulf St",
    "Ligaya",
    "Lily",
    "Luzon Ave",
    "Manuel C. Briones",
    "Marcelino",
    "Marine Rd",
    "Mirasol",
    "N. Romualdez",
    "Navy Rd",
    "Norwalk Rd",
    "Odonnel Rd",
    "Pantaleon Palayo",
    "Paraluman",
    "Paraluman",
    "Pearl St",
    "Rangers Rd",
    "Republic Ave",
    "Ricardo Mepomuceno",
    "Riverside St",
    "Rose St",
    "Ruby St",
    "S. Moldero",
    "Saint Paul Street",
    "Salumbides",
    "Sampaguita Ave",
    "Sampaguita Street",
    "San Isidro St",
    "San Lorenzo Rulz",
    "San Simon",
    "Santa Maria St",
    "Santa Monica St",
    "Santan",
    "Santo Rosario St",
    "Sapphire Street",
    "St. Anthony St",
    "St. Florence Alley",
    "St. Joseph St",
    "St. Joseph-Sta. Catalina Path",
    "St. Michael St",
    "St. Peter St",
    "Sta. Catalina St",
    "Sto. Domingo St",
    "Sto. Ireneo",
    "Teodoro Sandiko",
    "Torrance",
    "USAFFE Rd",
    "Veterans Ave",
    "Vicente S. Encarnacion",
    "Victorino Salazar",
    "Zuzuarregui St",
];

export const payatas = [
    "Acacia Street",
    "Acorda Street",
    "Agoho Street",
    "Alley A",
    "Alley B",
    "Alley C",
    "Alley D(footway)",
    "Alley E",
    "Anahaw Street",
    "Apo Street",
    "Arayat Street",
    "Azucena",
    "Banahaw Street",
    "Banawe Street",
    "Bansalangin Street",
    "Beginners' Trail(path)",
    "Bert Loop",
    "Bicol",
    "Bicol Extension",
    "Bulacan",
    "Cadena de Amor",
    "Champaca",
    "Clemente Street",
    "Cordillera Street",
    "Cresta Street",
    "Dahlia",
    "Dama de Noche",
    "Dama de Noche Street",
    "Dinorado Street",
    "Diwata Street",
    "Durian Street",
    "Eagle Street",
    "Empire Hilltop",
    "Fatima Street",
    "Gumamela Street",
    "Halcon Street",
    "Holy Family Street",
    "IBP Road(secondary)",
    "Ilang-Ilang Street(tertiary)",
    "Iloilo(footway)",
    "Iriga Street",
    "Kamuning Street",
    "Katipunan Avenue",
    "Legaspi",
    "Leyte",
    "Lower Empire",
    "Lunas Street",
    "Mabolo Street",
    "Mahogany Street",
    "Makiling Street",
    "Malaya Street",
    "Mayon Street",
    "Molave Street",
    "Narra Street",
    "Orchids Street",
    "Palayan Street",
    "Palochina Street",
    "Pampanga",
    "Pangga",
    "Payatas Road(secondary)",
    "Perimeter Route(service)",
    "Perpetual Help Street",
    "Phase 2",
    "Phase 3 Area A(footway)",
    "Phase 3 Area B",
    "Phase 3 Block 1",
    "Phase 3 Block 3",
    "Phase 3 Block 7",
    "Purok 10",
    "Purok 11(footway)",
    "Purok 12",
    "Purok 5",
    "Purok 6(footway)",
    "Purok 7(footway)",
    "Purok 8(footway)",
    "Purok 9(footway)",
    "Rose Street",
    "Samar",
    "Samat Street",
    "Sampaguita",
    "Sampaguita Extension",
    "Sampaguita Street",
    "San Juan Bautista Street",
    "San Miguel Street",
    "Sandakot",
    "Santa Fe",
    "Santan Street",
    "Santo Niño Interior",
    "Santo Niño Street",
    "Santo Tomas Street",
    "Secreto de Amor",
    "Sierra Madre Street",
    "Silay Street",
    "Sorsogon",
    "Taal Street",
    "Tanguile Street",
    "View Deck Route(service)",
    "Visayas(tertiary)",
    "Waling-waling",
    "Wayan Street",
    "Zamboanga Street",
];