export const amihan = [
    "Aguho",
    "Alley 1 (footway)",
    "Alley 2 (footway)",
    "Alley 4 (service)",
    "Amayan",
    "Anonas Street (secondary)",
    "Arangga",
    "Aurora Boulevard (primary)",
    "B. Gonzales Street",
    "Banaba",
    "Banuyo",
    "Batino Alley (footway)",
    "Batino Street (tertiary)",
    "Bignay Street",
    "Bocobo Street",
    "C. Aguinaldo Street",
    "Callejon (service)",
    "Chico Street (secondary)",
    "Dao",
    "Dap Dap",
    "Dungon Street",
    "Durian Street",
    "Evangelista Street",
    "F. Calderon Street",
    "F. Castillo Street (tertiary)",
    "Guijo",
    "Guyabano Street",
    "Ipil",
    "Jose P. Rizal Street (tertiary)",
    "K-10th Street",
    "K-6th Street",
    "Kaimito Street",
    "Kalantas",
    "Kamagong",
    "Kamagong Exit",
    "Kamias Street Extension (tertiary)",
    "Kubili Street",
    "Langka Street (tertiary)",
    "Lanzones",
    "Lanzones Street",
    "Lauan",
    "Laurel Street",
    "M. Delos Santos Street",
    "Makadios Street",
    "Malong Street",
    "Marang Street",
    "Melissa Drive",
    "Molave Street (tertiary)",
    "Naranghita Street",
    "Narra Alley 3 (service)",
    "Narra Street (tertiary)",
    "Pajo Street",
    "Siniguelas Street",
    "Supa (footway)",
    "Talisay",
    "Tanguile (footway)",
    "Tindalo Street",
    "V. Luna Road Extension",
    "Yakal"
];

export const bagumbuhay = [
    "15th Avenue (secondary)",
    "18th Avenue",
    "20th Avenue (secondary)",
    "21st Avenue",
    "Antonio Luna",
    "Aurora Boulevard (primary)",
    "Aurora Boulevard (primary)",
    "Don Jose",
    "E. Evangelista",
    "Ermin Garcia Street (tertiary)",
    "F. Castillo Extension",
    "F. Castillo Street",
    "G. H. del Pilar Street",
    "Interior Miguel Malvar (footway)",
    "J. Bugallon",
    "Kalantiyaw",
    "La Salle Street",
    "Magat Salamat Extension",
    "Miguel Malvar",
    "Miguel Malvar Extension",
    "Mirasol Street",
    "Monterey Street",
    "Notre Dame",
    "P. Tuazon Boulevard (secondary)",
    "P. Zamora",
    "Potsdam Street",
    "Rochester Street",
    "Trinity Street",
]

export const bagumbayan = [
    "1st Street",
    "3rd Street",
    "4th Street",
    "Achilles",
    "Adonis Street",
    "Andromeda",
    "Apollo Street",
    "Astoria Street",
    "Atlas Street",
    "Berlinville Lane",
    "C-5-Bonny Serrano Flyover (primary)",
    "Calypso",
    "Calypso Street",
    "Cecilleville Street",
    "Citywalk 1 (pedestrian)",
    "Citywalk 2 (footway)",
    "Colonel Bonny Serrano Avenue (primary)",
    "Del Rosario (footway)",
    "E-Commerce Avenue (tertiary)",
    "E. Rodriguez Jr. Avenue (primary)",
    "Eastwood Avenue (tertiary)",
    "Economia Street (tertiary)",
    "Fernsville Street",
    "Fuente Circle (pedestrian)",
    "Greenhill Street",
    "Industria Street (tertiary)",
    "Italia Loop",
    "J. M. Basa Drive",
    "Jamaica Street",
    "Kew Garden Street",
    "Manggahan",
    "Mercury Avenue",
    "Oakville Street",
    "Obrero",
    "Odysseus Street",
    "Orchard Road (tertiary)",
    "Palm Tree Avenue (tertiary)",
    "Paris Street",
    "Penelope Lane",
    "Poseidon Street",
    "Queensville Drive",
    "Queensville Street",
    "Red Arrow Street",
    "Richmond Road (tertiary)",
    "Rivera Street",
    "Riverdale Street",
    "Saint Pio Access Road (service)",
    "San Gabriel (service)",
    "San Jose Street",
    "San Pablo (path)",
    "San Pablo 1 (path)",
    "San Pablo 2",
    "San Roque",
    "Santa Maria (path)",
    "Santo Niño (service)",
    "Santo Tomas (service)",
    "Sword Tail",
    "Tawiran",
    "Titan Street",
    "Troy",
    "Union Street (tertiary)",
    "Victorino Alley",
    "Wealth (service)",
    "White Field Street",
    "Woodside Street",
    "Yellowstone Street"
];

export const bayanihan = [
    "Jose P. Rizal Street (tertiary)",
]

export const blueridgea = [
    "Highland Drive",
    "Jose P. Rizal Street (tertiary)",
    "Katipunan Avenue (primary)",
    "Libis Tunnel (primary)",
    "P. Pelaez",
    "P. Tuazon Boulevard (secondary)",
    "Pasaje de la Paz Street",
    "Pedro C. Martinez Street",
    "Rajah Matanda Street (tertiary)",
    "Sunrisers Street",
    "Tom Castro Street (tertiary)",
]

export const blueridgeb = [
    "Highland Drive",
    "Jose P.Rizal Street(tertiary)",
    "Katipunan Avenue(primary)",
    "Libis Tunnel(primary)",
    "P.Pelaez",
    "P.Tuazon Boulevard(secondary)",
    "Pasaje de la Paz Street",
    "Pedro C.Martinez Street",
    "Rajah Matanda Street(tertiary)",
    "Sunrisers Street",
    "Tom Castro Street(tertiary)",
]

export const campaguinaldo = [
    "10th Avenue",
    "11th Avenue",
    "12th Avenue",
    "13th Avenue",
    "14th Avenue",
    "15th Avenue (secondary)",
    "3rd Avenue",
    "4th Avenue",
    "5th Avenue",
    "6th Avenue",
    "7th Avenue",
    "9th Avenue (tertiary)",
    "Annapolis Street (tertiary)",
    "Arturo Enrile Avenue",
    "Brigadier General Delos Reyes Street",
    "Camacho Street",
    "Camp Aguinaldo Bike Trail (path)",
    "Capinpin",
    "Capinpin Avenue (service)",
    "Colonel Boni Serrano Avenue (secondary)",
    "Columbia Street",
    "Crame Avenue (service)",
    "De Jesus Avenue (service)",
    "De Los Reyes Street (service)",
    "EDSA (secondary)",
    "Florida Street",
    "General de los Reyes Street (service)",
    "General P. Santos Avenue",
    "General Santos Street",
    "Guido Avenue",
    "Natividad",
    "Santolan (footway)",
    "Segundo Avenue",
    "Solomon Street",
    "V. V. Soliven Driveway (service)"
];

export const claro = [
    "Acacia",
    "Aguho",
    "Almon",
    "ALMASIGA",
    "ANISLAG",
    "AKLE",
    "AMUGIS",
    "AMAYAN",
    "APITONG",
    "ANUBING",
    "ARANGA",
    "LANGKA",
    "NARRA",
    "TINDALO",
]

export const dioquinozobel = [
    "Diego Silang St.",
    "General Lizardo St.",
    "M.T.Dioquino St.",
]

export const duyanduyan = [
    "Aguho",
    "Almaciga",
    "Dapdap",
    "Guijo",
    "Ipil",
    "Kalantas",
    "Kamagong",
    "Molave",
    "Narra",
    "Tindalo",
]

export const erodriguez = [
    "Annapolis",
    "Cambridge",
    "Columbia",
    "Ermin Garcia",
    "Harvard",
    "Imperial",
    "Montreal",
    "Oxford",
    "Purdue",
    "Standford",
    "St. Mary",
    "Wespoint",
    "Yale",
]

export const eastkamias = [
    "Anonas",
    "Kasing kasing",
    "K-I",
    "K-J",
    "K-6th",
    "K-7th",
    "K-8th",
    "K-9th",
    "K-10th",
]

export const escopa1 = [
    "Escopa 1",
    "P. Burgos",
    "P. Tuazon",
]

export const escopa2 = [
    "Mayor Santos Dizon",
]

export const escopa3 = [
    "P. Burgos",
    "Road 4"
]

export const escopa4 = [
    "Escopa 1",
    "Escopa 2",
    "Libis",
    "P.Mejia",
]

export const loyolaHeights = [
    "A. Melchor",
    "Alta Vista",
    "A Regidor",
    "Avelino",
    "B. Gonzales",
    "C. Salvador",
    "Dormitory",
    "Escaler",
    "Esteban Abada",
    "F. Collantes",
    "Father Arrupe",
    "Father Masterson Dr",
    "F dela rosa",
    "Garcia",
    "Guerrero",
    "J. Bocobo",
    "J.P. Laurel",
    "Jade",
    "Jocson",
    "Laurel",
    "Loyola Drive",
    "Marymount",
    "Melissa Dr",
    "Moro Lorenzo Wy",
    "Nicanor Reyes",
    "Osmena",
    "Palma",
    "Parade Loop",
    "Park 9",
    "Paseo de Reily",
    "Quezon",
    "Quisumbing Drive",
    "Rosa Alvero",
    "Roxas",
    "Ruby",
    "Seminary Rd.",
    "T. Evangelista",
    "Thornton Drive",
    "Topside Valley",
    "University Rd",
    "Villa Aurora"
];

export const mangga = [
    "20th Avenue"
];

export const marilag = [
    "A. De Lagaspi",
    "A. Luna",
    "A. Novales",
    "Angles",
    "Aguado",
    "C. Aguinaldo",
    "Cabuco",
    "Calderon",
    "Camerino",
    "Dagohoy",
    "Jose Ma. Hugo",
    "Nay-isa",
    "H. Unrubia",
    "J. Ponze",
    "J.P Rizal",
    "Malong",
    "M. Pauza",
    "Maga Salamat",
    "P. Ladia"
];

export const masagana = [
    "Alimudin",
    "Callejon 1",
    "F. Salalilla",
    "J. Bracken",
    "J. Ocampo",
    "J. Perez",
    "Jose P. Rizal Street",
    "Kalantiaw",
    "Lakandula",
    "M. Gregorio Street",
    "M. T. Dioquino",
    "Rajah Matanda",
    "Tamblot"
];


export const milagrosa = [
    "De Legaspi",
    "Alvarez",
    "Ali Mudin",
    "Belarmino",
    "D. Tirona",
    "Delos Reyes",
    "F, Salalilla",
    "Lakandula",
    "Pasahe Dela Paz",
    "P. Pelaez",
    "Sanrisers",
    "Tomas Mascardo",

]

export const matandangbalara = [
    "Bonifacio Street",
    "Abraham Street",
    "Acacia Street",
    "Ace Street",
    "Adams Street",
    "Adams Street Extension",
    "Aduana Street",
    "AFP Road",
    "Aglipay Street",
    "Aguinaldo Street",
    "Albany Street",
    "Almacenes Street",
    "Almaciga Street",
    "Alpha Street",
    "Amber Street",
    "Amsterdam Drive",
    "Anda Street",
    "Anonas Street",
    "Apacible Street",
    "Apitong Street",
    "Apollo Street",
    "Arsobispo Street",
    "Artemis Street",
    "Athena Street",
    "Atis Street",
    "Ayala Heights Drive",
    "Balagtas Street",
    "Balintawak Street",
    "Bataan Place",
    "Bataan Street",
    "Bayabas Street",
    "Bayanihan Road",
    "Beaterio Street",
    "Berlin Avenue",
    "Betany Street",
    "Biak Na Bato Street",
    "Bilaan Street",
    "Block 2 Street",
    "Bonn Street",
    "Brussels Street",
    "Budapest Street",
    "C-5 Expressway (proposed)",
    "Cabildo Street",
    "Calderon Compound",
    "Calderon Street",
    "Camachile Street",
    "Camia Street",
    "Canterbury Street",
    "Capitol Green Street",
    "Capitol Hills Drive",
    "Caracas Street",
    "Cayetano Arellano Street",
    "Chico Street",
    "Clark Street",
    "Clubhouse Drive",
    "Cologne Street",
    "Commonwealth Avenue",
    "Commonwealth Villi",
    "Congressional Avenue Extension",
    "Copenhagen Street",
    "Corregidor Street",
    "Crystal Street",
    "Dagohoy Street",
    "Dahlia Street",
    "Daisy Street",
    "Dalanghita Street",
    "Dalton Pass Street",
    "Dao Street",
    "Dapitan Street",
    "David Street",
    "Del Pilar Street",
    "Delta Street",
    "Diamond Drive",
    "Diliman Street",
    "Doña Felicidad Street",
    "Doña Filomena Street",
    "Doña Pacita Street",
    "Doña Pilar Street",
    "Don Antonio, Sr. Street",
    "Don Enrique Street",
    "Don Matias Street",
    "Durian Street",
    "E. Aguinaldo Street",
    "E. Jacinto Street",
    "E. Verde Compound",
    "Eagle Street",
    "East de Leon Drive",
    "Edades Drive",
    "Elijah Street",
    "Escuela Street",
    "Ezekiel Street",
    "F. Agoncillo Street",
    "F. Amorsolo Street",
    "F. Ma. Guerrero Street",
    "Fairway Street",
    "Guildford Street",
    "Heartbreak Hill (locality)",
    "J.P. Rizal Street",
    "Mactan Street",
    "Mabini Street",
    "Magnolia Street",
    "Manors Celebrity Place",
    "Pines Street",
    "Sampaguita Street",
    "South Zuzuarregui",
    "Upsilon Drive"
];

export const pansol = [
    "Aruba",
    "Betany",
    "Bagjao",
    "Bagobo",
    "Bilaan",
    "Carriedo",
    "Chile",
    "Fitzgerald",
    "Gaddang",
    "Honduras",
    "H. Ventura",
    "Ibang",
    "Ifugao",
    "Ilongot",
    "Kalinga",
    "L. Wood",
    "Mactan",
    "Mangyan",
    "Maranao",
    "Tasaday",
    "Tausing",
    "Venezuela",
    "Yakan"
];

export const quirino2A = [
    "Anonas Street",
    "Bignay Street",
    "Chico Street",
    "Kubili Street",
    "Lanzones Street",
    "Marang Street",
    "Naranghita Street",
    "Pajo Street",
    "Caimito Street",
    "Rimas Street"
];

export const quirino2B = [
    "Bignay Street",
    "Chico Street",
    "Durian Street",
    "Lanzones Street",
    "Guyabano Street",
    "Marang Street",
    "Naranghita Street",
    "Pajo Street",
    "Tampoy Street",
    "Anonas Street"
];

export const quirino2C = [
    "Bignay Street",
    "Chico Street",
    "Durian Street",
    "Siniguela Street",
    "Pajo Street",
    "Langka Street"
];

export const quirino3A = [
    "Anonas Street",
    "Molave Street",
    "Dao Street",
    "Aurora Blvd"
];

export const saintIgnatius = [
    "1st Street",
    "2nd Street",
    "3rd Street",
    "4th Street",
    "Astoria Street",
    "Fordham Street",
    "Harvard Street",
    "Jamaica Street",
    "Kew Garden Street",
    "Paris Street",
    "Riverdale Street",
    "Riviera Street",
    "Woodside Street"
];

export const sanRoque = [
    "15th Ave Street",
    "16th Ave Street",
    "17th Ave Street",
    "18th Ave Street",
    "19th Ave Street",
    "20th Ave Street",
    "2nd Camarilla Street",
    "3rd Camarilla Street",
    "5th Camarilla Street",
    "6th Camarilla Street",
    "Dioquino Street",
    "Don Jose Street",
    "G.H Del Pilar Street",
    "Kalantiaw Street",
    "Mirasol Street",
    "Monterey Street",
    "P. Zamora Street",
    "Princeton Street",
    "Rochester Street",
    "Trinity Street"
];

export const silangan = [
    "15th Ave Street",
    "Albany Street",
    "Columbia Street",
    "Ermin Garcia Street",
    "Illinois Street",
    "K-J Street",
    "La Salle Street",
    "Miami Street",
    "Norte Dame Street",
    "Notre Dame Street",
    "Pittsburgh Street",
    "Potsdam Street"
];

export const socorro = [
    "10th Ave Street",
    "11th Ave Street",
    "12th Ave Street",
    "13th Ave Street",
    "14th Ave Street",
    "5th Ave Street",
    "6th Ave Street",
    "7th Ave Street",
    "8th Ave Street",
    "9th Ave Street",
    "Gen. Aguinaldo Street",
    "General Aguinaldo Ave Street",
    "General Mc Arthur Ave Street",
    "General Romulo Ave Street",
    "General Roxas Ave Street",
    "Harvard Street",
    "Main Ave Street",
    "P.Tuazon Blvd Street",
    "PUJ Ln Street",
    "Stanford Street",
    "Times Square Ave Street"
];

export const tagumpay = [
    "20th Ave Street",
    "21st Ave Street",
    "Century Comp Street",
    "P.Tuazon Blvd Street",
    "Zobel Street"
];

export const ugongNorte = [
    "Amorsolo Street",
    "Arcadia Ave Street",
    "Bautista Street",
    "Bluebird Street",
    "Cameron Street",
    "Castrillo Street",
    "Cesar Legaspi Street",
    "David Street",
    "Don Vicente Madrigal Ave Street",
    "E.Abello Street",
    "Edades Street",
    "Flamingo Street",
    "Fuentes Street",
    "Giraffe Street",
    "Hechanova Street",
    "Joaquim Street",
    "Joya Street",
    "King Fisher Street",
    "Lark Street",
    "Luna Street",
    "Luz Cir Street",
    "Navarro Street",
    "Nightingale Street",
    "Nuyda Street",
    "Ocampo Street",
    "Oriole Street",
    "Owl Street",
    "Parakeet Street",
    "Radeo Dr. Street",
    "Roces Cir Street",
    "Sanso Street",
    "Sparrow Street",
    "Swallow Dr. Street",
    "Tabuena Street",
    "Temple Dr. Street",
    "Vicente Puyat Ave Street",
    "Warbler Street",
    "Woodpecker Street",
    "Young Street",
    "Zalameda Street"
];

export const villaMariaClara = [
    "Alimudin Ext Street",
    "Alvarez Street",
    "J.Ocampo Street",
    "J.P Rizal Street",
    "P.Pelaez Street",
    "P.Tecson Street",
    "Tomas Mascardo Street"
];

export const westKamias = [
    "Edsa N Svc Rd",
    "K-10th Street",
    "K-6th Street",
    "K-7th Street",
    "K-8th Street",
    "K-9th Street",
    "K-G Street",
    "K-H Street",
    "K-I Street",
    "Kamias Rd"
];

export const whitePlains = [
    "1st Street",
    "Apollo Street",
    "Cecilleville Street",
    "Charleyville Street",
    "Dainty Street",
    "Derby Street",
    "Fernsville Street",
    "Fordham Street",
    "Greystone Street",
    "Kingsville Street",
    "Nathan Street",
    "Oakville Street",
    "Pinesville Street",
    "Poseidon Street",
    "Queensville Street",
    "Red Arrow Street",
    "Roseville Street",
    "Sarangaya Ave Street",
    "Titan Street",
    "Whitefield Ave Street",
    "Yellowstone Street"
];
