export const bagbag = [
    "Aquarius St",
    "Artemio",
    "B. Karaan",
    "Callejon-Cruz",
    "Capricorn",
    "Daniel Street",
    "De amor",
    "Enoch St",
    "Esau",
    "Esther St.",
    "Ezekiel St",
    "Ezra",
    "F Delos Santos St.",
    "Gold St",
    "Gumamela",
    "Ilang-Ilang",
    "Isaac",
    "Jasmin St.",
    "Jeremiah St",
    "Job St",
    "Joel",
    "John",
    "Jonas St.",
    "Joshua St",
    "Judith St.",
    "King Alexander St.",
    "King Augustus",
    "King Charles Ext",
    "King Charles St.",
    "King Christian Ext",
    "King Christopher St.",
    "King Constantine Ext",
    "King Edward",
    "King Ferdinand",
    "King Francis",
    "King Frederic",
    "King George St",
    "King Henry St",
    "King James St",
    "King Micheal St",
    "King Nicholas St",
    "King Paul St",
    "King Phillip St",
    "King Williams St",
    "Leon Cleofas Street",
    "Lilac",
    "Luke St",
    "Magnolia",
    "Magno St.",
    "Mark St",
    "Moses St",
    "Noah St",
    "Ocean Park",
    "Pascual Ave",
    "Poinsetia",
    "Remarville St",
    "Rosal St",
    "Ruby St.",
    "Ruth",
    "Sagitarius",
    "Saint Micheal",
    "Sampaguita",
    "Santan",
    "Saul",
    "Sinforosa",
    "T. Carreon",
    "Taurus",
    "Topaz",
    "Urcia Street",
    "Venus St",
    "Virgo",
    "Waling Waling"
];

export const capri = [
    "Area 4",
    "Banahaw",
    "Lawaan St",
    "Mangga St",
    "Narra St.",
    "Talisay St",
    "Yakal St"
];

export const fairview = [
    "Austin",
    "Bel Air",
    "Bergamo Ln",
    "Biscayne",
    "Buick",
    "Camaro St",
    "Camel",
    "Cavalier St",
    "Colt",
    "Consul St",
    "Coronet",
    "Corvette",
    "Dart St",
    "Datsun",
    "Diamond",
    "Dodge",
    "Dunhill St",
    "Edsel",
    "Emerald",
    "Escort",
    "Fairlane",
    "Ferrari",
    "Fiat St",
    "Fortune Street",
    "Garnet",
    "Goldman St",
    "Hillman St",
    "Holden",
    "Hunter St",
    "Iceland St",
    "Impala",
    "Jade",
    "Jaguar",
    "Kool St",
    "Malibu",
    "Marlboro St",
    "Mercury",
    "Mustang",
    "Narra St",
    "Newport St",
    "Opal",
    "Pall Mall St",
    "Paxton St",
    "Pearl",
    "Piedmont St",
    "Pontiac St",
    "Ruby",
    "Sapphire",
    "Sitio Ruby Street",
    "Spud Street",
    "Topaz",
    "Turquoise",
    "Valiant",
    "Venice Ln",
    "Viceroy St",
    "Viking St",
    "Windsor",
    "Winston St"
];

export const greaterLagro = [
    "Amor",
    "Ati-Atihan",
    "Bida Sari",
    "Bighani",
    "Bota Flores St",
    "Brera St",
    "Bronzetti",
    "Cana St",
    "Candelaria St",
    "Caridad",
    "Castello St",
    "Corpus Christi",
    "Diwata St",
    "Domingo de Ramos",
    "Duomo St",
    "Eastern St",
    "Elvazia",
    "Ezperanza St",
    "Fe",
    "Florante at Laura",
    "Flores De Mayo",
    "Gesu St",
    "Gramsci",
    "Handiong",
    "Harana",
    "Haring Constatino",
    "Hariraya",
    "Hermano Mayor",
    "Ibalon",
    "Inang Bayan",
    "Juego de Prenda",
    "Kudyapi",
    "Lakambini",
    "Lam-ang St",
    "La Naval",
    "Longinus",
    "Luningning",
    "Magenta St",
    "Malakas at Maganda St",
    "Maria Makiling",
    "Maricudo",
    "Melchiorre Street",
    "Misa de Galo",
    "Moscova",
    "Napoleon",
    "Noche Buena",
    "Pabasa St",
    "Pantomina Mayor",
    "Panyo Palaran St",
    "Putol na Daan",
    "Ripamonti",
    "Sforza",
    "Venezia"
];

export const gulod = [
    "Araceli",
    "Bagong Tunay",
    "Bayes",
    "Belen",
    "Commissioner",
    "Congressman",
    "Consuelo",
    "Continental",
    "Dexter",
    "Engracia",
    "Ester",
    "Florentina",
    "Forest Hill Dr",
    "Gloria",
    "Governor",
    "Granada",
    "Jewel",
    "Kabagong Tauhan",
    "Kabilogan",
    "Kabuhayan",
    "Kadalagahan",
    "Kalayaan",
    "Kalinisan",
    "London Dr",
    "Luz",
    "Luzviminda",
    "Maligaya",
    "Maningning",
    "Marcosin",
    "Margarita",
    "Marianito",
    "Martinez",
    "Masaya",
    "Midway",
    "Nazario",
    "Nellie",
    "Nenita",
    "Payapa",
    "Pilaring",
    "President",
    "Pulang Bituin",
    "Queens",
    "San Augustine",
    "San Ignacio",
    "San Juan",
    "San Julian",
    "San Lazaro",
    "San Luis",
    "San Martin",
    "San Miguel",
    "San Nicholas",
    "San Pedro",
    "Santa Marcelo St",
    "Senading",
    "Senator St",
    "Severina",
    "Sta, Trinidad",
    "Sta, Veronica",
    "Sta. Barbara",
    "Sta. Eleuteria",
    "Sta. Isabel",
    "Sta. Maxima",
    "Sta. Placida",
    "Sta. Veronica",
    "St Anthony",
    "Susana",
    "Tagumpay Dr",
    "Temple St",
    "Villareal"
];

export const kaligayahan = [
    "2nd Main",
    "Agoo",
    "Alley",
    "Apollo",
    "Aprohdite",
    "Arcadia",
    "Aringay",
    "Assyra",
    "Athena",
    "Babylonia",
    "Bach",
    "Bacnotan",
    "Balaoan",
    "Bangar",
    "Bauang",
    "Beethoven",
    "Berlios",
    "Bethel",
    "Bethlehem",
    "Brahms",
    "Camilo Osias",
    "Canaan",
    "Cardinal",
    "Carmen",
    "Chikadee",
    "Chopin",
    "Colosse",
    "Concord",
    "Corinthians",
    "Damortis",
    "Debussy",
    "Del Pilar",
    "Diamond Dr",
    "Eagle",
    "Ephesus",
    "Falcon",
    "Franville II",
    "Galathia",
    "Galilee",
    "Gomez",
    "Greecia",
    "Griego",
    "Handel",
    "Haydn",
    "Helena",
    "Hercules",
    "James",
    "Jerusalem",
    "John",
    "Junio",
    "Jupiter",
    "King Fisher",
    "Lovebird",
    "Luke",
    "Luna",
    "Mabini Dr",
    "Mark",
    "Matthew",
    "Mendelssohn",
    "Mozart",
    "Naguilian",
    "Nightingale",
    "Olympus",
    "Parnassus",
    "Parthenon",
    "Penguin St",
    "Pizza",
    "Rachel",
    "Ravel",
    "Salvia",
    "San Diego Dr",
    "San Fernando",
    "Schubert",
    "Schumann",
    "Sinai",
    "Skylar",
    "Strauss",
    "Supiden",
    "Vasilion",
    "Venue",
    "Victoria",
    "Vivaldi",
    "Wagner",
    "Woodpecker",
    "Zabarte Ext",
    "Zion",
    "Zues"
];

export const nagkaisangNayon = [
    "Arayat",
    "B. Dantes",
    "Babilonia",
    "Bartolome Dr",
    "Blue Ridge",
    "Broadway",
    "Calla St",
    "Carmencita",
    "Dahlia",
    "Diamond",
    "Dominga",
    "Domingo",
    "East St",
    "Eduardo",
    "Emerald",
    "Fidel Cruz",
    "Fulgencio Rd",
    "Gerryvile",
    "Gethsemane",
    "Gozum St",
    "Hipolito St",
    "Israel",
    "Jordan",
    "Juan",
    "Katipunan",
    "Lapulapu",
    "Luisito",
    "Maria",
    "Mayon St",
    "Merry Mount",
    "Misty",
    "Molave Dr",
    "Morning Sun",
    "North St",
    "Opal",
    "P. Dela Cruz",
    "Pablo",
    "Pascola A",
    "Pedro Cruz",
    "Pesin",
    "Princess Diana",
    "Queen Alexandra",
    "Queen Rd",
    "Queen Victoria",
    "Rebisco Rd",
    "Reliance",
    "Reynaldo",
    "Robina Rd",
    "Rome",
    "Rosal",
    "Samonte",
    "San Dionisio",
    "San Fernando Rd",
    "San Ildefonso Rd",
    "San Ildenfonso",
    "San Pablo",
    "Santa Clara Villas",
    "Sodiba Rd",
    "St Anthony",
    "St james",
    "St John",
    "St Joseph",
    "St Jude",
    "St Luke",
    "St Mary",
    "St Michael",
    "St Paul",
    "St peter",
    "Sunset Dr",
    "Syria",
    "Terio",
    "Urbana Drive",
    "Wales",
    "West St",
    "Yellow Stone rd"
];

export const northFairview = [
    "Accounting",
    "Adrian",
    "Alarka",
    "Alden",
    "Alfa",
    "Alton St",
    "Alzen",
    "Ames",
    "Antler",
    "Archer",
    "Argos",
    "Ashley",
    "Aspen",
    "Atherton",
    "Auburn",
    "Avalon",
    "Avon",
    "Axtell",
    "Aynor",
    "Badger",
    "Bangkal",
    "Banning",
    "Bascom",
    "Bayer",
    "Bergen",
    "Bonner",
    "Braceville",
    "Bradford",
    "Bradley",
    "Bremley",
    "Bristol St",
    "Bronson St",
    "Bronx",
    "Bryant Street",
    "Burbank",
    "Burke",
    "Byron",
    "Collection",
    "Computer St",
    "Contribution",
    "Dao",
    "Dapdap",
    "Dinar",
    "Dollar",
    "Engineering",
    "Guijo",
    "Investment",
    "Ipil",
    "Kalantas",
    "Lauan",
    "Legal",
    "Loans",
    "Mahogany",
    "Malipajo",
    "Medical",
    "Medicare",
    "Molave",
    "Narra",
    "Pension",
    "Pound",
    "Registration",
    "Riyal",
    "Schilling",
    "Sheker",
    "Siete Palabras St",
    "Talisay",
    "Treasury",
    "Yakal",
    "Yen",
    "Yuan"
];

export const novalichesProper = [
    "Buenamar Dr",
    "Dona Isaura",
    "Dona Rosario",
    "Lourdes",
    "Maagap",
    "P. urduja",
    "Panday Pira St",
    "Petronia St",
    "Prinsipe Tupas",
    "Ramirez",
    "Rosal Street",
    "Sarmiento"
];

export const pasongPutikProper = [
    "Bel-Air",
    "Cooper",
    "Greenwich",
    "Kingston",
    "Stewart"
];

export const sanAgustin = [
    "Apitong",
    "Bethzaida",
    "Biglang Awa",
    "Ciara St.",
    "Dau St",
    "Del Rey",
    "Diego Silang",
    "Dona Azucena St",
    "Doña Engracia St",
    "Don Alejandro",
    "Dona Maria",
    "Don Benjamin",
    "Don Maria",
    "Don Mariano",
    "Don Philip",
    "E Aguinaldo",
    "Eden",
    "Emma",
    "Emmanuel",
    "E Quirino",
    "Fatima",
    "General Malvar",
    "Happiness",
    "Hercules",
    "J.P Laurel",
    "Jordan",
    "Joselito",
    "Joyville Dr",
    "Juancho St.",
    "Kamagong",
    "Lawaan",
    "Magsaysay",
    "Mango",
    "Molave",
    "M Roxas",
    "Osmena Right",
    "P. Rivera",
    "Paraiso",
    "Patnubay",
    "Pearl",
    "Platinum",
    "S Osmena Sr",
    "Tindalo",
    "Yakal"
];

export const sanBartolome = [
    "1st",
    "2nd",
    "A Bonificaio St",
    "ACF Rd",
    "Acme",
    "Amethyst",
    "Aratiles St.",
    "Aries",
    "Armani",
    "Assisi",
    "Bayani",
    "Begonia",
    "Beta",
    "B Evangelista Dr",
    "Blue",
    "Blue Bird",
    "Bvlgari St",
    "Camachile St",
    "Camia",
    "Champaca St",
    "Charity",
    "Clara",
    "CP Romulo",
    "Crysanthemum St",
    "Dahlia",
    "Diamond",
    "Dillgience",
    "Dillgience",
    "Dior St",
    "Dizon",
    "East Point",
    "E Berkely",
    "Efficience",
    "E Los Angeles",
    "Emerald",
    "Espoleto",
    "Ester",
    "Faith",
    "Fern",
    "Fern",
    "Franco St",
    "Gamma",
    "Garcia",
    "Garcia",
    "Gemini",
    "Gemini",
    "Generosity",
    "Gold",
    "Goodwill",
    "Greccio",
    "Green",
    "Gucci",
    "Helpful",
    "Ilang-Ilang St",
    "Industry",
    "Ivory",
    "Jade",
    "Joy",
    "Kapok Street",
    "King William St",
    "Lapuz",
    "Laverna",
    "Leo",
    "Libra",
    "Lime",
    "M. Jacob",
    "Macapagal",
    "Madre Caco St.",
    "Manila Memorial",
    "Marcos",
    "Mint",
    "Myrtle",
    "Narra St",
    "Olive",
    "Omicron",
    "Orange",
    "Oregon",
    "Percincula",
    "Perugia",
    "Pink St",
    "Prada",
    "Purity",
    "Quezon",
    "Quirino",
    "Rain",
]

export const santaLucia = [
    "Dela Cruz",
    "Mabini",
    "Agoncillo St",
    "Balagtas",
    "Beryl Street",
    "Bonifacio St.",
    "Bugos",
    "Bukaneg",
    "Diego Silang",
    "Donafield St",
    "F. Calderon",
    "Galvez",
    "Gomez",
    "J. Basa",
    "Jaconto",
    "J Luna",
    "Jose Abad Santos",
    "JP Rizal",
    "M. Aquino",
    "Malvar",
    "Marco Polo",
    "MH Del Pilar",
    "Naning Ponce",
    "Natividad",
    "P. Paterno",
    "Paguio Compound",
    "R. Humabon",
    "Rajah Soliman",
    "Rajah Sulayman",
    "Salvador St",
    "Simeon Castro",
    "Sta. Lucia",
    "T. Alonzo",
    "Visayas",
    "Zamora"
];

export const santaMonica = [
    "Aberdeen",
    "Adelfa",
    "Amos",
    "Atherton",
    "Atis",
    "Avocado",
    "Azucena",
    "Azul",
    "Baht",
    "Bayabas",
    "Begonia",
    "Beirut",
    "Berlin",
    "Buogainvilla",
    "Caimito",
    "Champaca",
    "Consolacion",
    "Cypress",
    "Dahlia",
    "Dama De Noche",
    "Daniel",
    "Dapdap",
    "Dayap Dalanghita",
    "Dinar",
    "Dirham",
    "Dollar",
    "Dona Adela",
    "Don Ciriaco",
    "Dr. Villareal St.",
    "Drachma",
    "Dumalay",
    "Durian",
    "E.G. Fernandez",
    "Encarnacion",
    "Fleur De Lis",
    "Forest Hill Dr",
    "Franc",
    "Geronimo",
    "Gladiola",
    "Granada",
    "Granate St",
    "Guijo",
    "Gumamela",
    "Herminia",
    "Hosea",
    "Ibong Pilak",
    "Idang Street",
    "Ilang-Ilang",
    "Isaiah",
    "Jeremiah",
    "Joan of Arc",
    "Job",
    "Joel",
    "Joshua",
    "Kamatsile",
    "Kampupot",
    "Kasoy",
    "Lira",
    "Luisito",
    "Lydua",
    "Mabolo",
    "Mangga",
    "Mariposa",
    "Mark",
    "Mayang Pula",
    "Micah",
    "Milenyo",
    "Milflores",
    "Morena Blanco",
    "Moses St",
    "Mt Apo",
    "Mt Arayat",
    "Mt Baco",
    "Mt Cresta",
    "Mt Everest",
    "Naranja",
    "N Labayani",
    "Northridge",
    "Orange",
    "Orchid",
    "Paguita St",
    "Peseta",
    "Pio",
    "Pitmini",
    "Pound",
    "Pugong Ginto",
    "Rand",
    "Riverside",
    "Riyal",
    "Rojo",
    "Rosal",
    "Rosas",
    "Rouble",
    "Rubia",
    "Rupee",
    "Sampaguita",
    "Sanggumay",
    "Santol",
    "Sarmiento",
    "Schilling",
    "Tatlong Hari",
    "Tsiko",
    "Vancouver",
    "Villa Verde",
    "Violeta",
    "Violeta Ext",
    "Virginia",
    "Waling-Waling",
    "Won",
    "Yakal",
    "Yen",
    "Yuan"
];