export const apolonioSamson = [
    "Acacia Drive",
    "Aguilar Street",
    "Andres Bonifacio Avenue",
    "Aniceta Street",
    "Antoniette Street",
    "Apacible Street",
    "Aranzanso Compound",
    "B. Oliveros",
    "Bagong Barrio",
    "Bahawan Street",
    "Balingasa Street",
    "Balintawak",
    "Balintawak Footbridge",
    "Belle Court",
    "Bellevue Drive",
    "Beryl Street",
    "Caroline Street",
    "Catherine Street",
    "Christian",
    "Christine Street",
    "Church Street",
    "Cloverleaf Drive",
    "Colosal Street",
    "Dancel Compound",
    "Dionisio Compound",
    "Dita Street",
    "Don Manuel Street",
    "East Service Road",
    "Eleven Road",
    "Eulogia Drive",
    "Evangeline Street",
    "F. Aguilar Extension",
    "Faith Street",
    "Fountain Drive",
    "Gardenia Lane",
    "Gardenia Loop",
    "Goodwill Compound",
    "Grace Avenue",
    "Harmony Street",
    "High Street",
    "Hope Street",
    "Howmart Road",
    "Interior 86",
    "Interior Kaingin Road",
    "J. Aquino Cruz Street",
    "J. Mariano Street",
    "Jade Street",
    "Josephine Street",
    "Joy Street",
    "Kaingin",
    "Kaingin Footbridge",
    "Kaingin Road",
    "Kaingin Road",
    "Katipunan Street",
    "Lily Street",
    "Lorraine Street",
    "M. H. del Pilar Street",
    "M. Viola Street",
    "Madelaine Street",
    "Magsalin",
    "Mahogany Drive",
    "Malasimbo Street",
    "Narra Alley",
    "North Park Drive",
    "North Park Lane",
    "Old Samson Road",
    "Oliveros Drive",
    "Oliveros Footbridge",
    "Palm Drive",
    "Picarra Street",
    "Q. Baetiong Drive",
    "R. Baetiong Drive",
    "Ruby Street",
    "Salazar Drive",
    "Sampaguita Street",
    "Sampaguita Street Extension",
    "Samuel Dee Street",
    "Santa Maria Compound",
    "Santo Domingo Avenue",
    "Sapphire Street",
    "School Street",
    "South Park Drive",
    "South Park Lane",
    "Sunflower Lane",
    "Taguilid Street",
    "Tinaduan Street",
    "Tuktukan Street",
    "Valentin Ventura Street",
    "Zircon Street"
];

export const baesa = [
    "Mang David Street",
    "Marangal",
    "Marikit",
    "Masagana",
    "Mendez Road",
    "Narra",
    "Oliveros Drive",
    "Osmeña",
    "Pacific",
    "Palm Road",
    "Quirino",
    "Quirino Highway",
    "Reposado",
    "Retales",
    "Reyes Compound",
    "Rivera",
    "Rivera–Apo Compound",
    "Rodriguez Drive",
    "Saint Dominic Drive",
    "Saint Loius Compound 6",
    "Saklolo",
    "Salazar Street",
    "Salvador",
    "San Francisco",
    "Santos Drive",
    "Segundo",
    "Virginia Drive",
    "Alley 1",
    "Argao Drive",
    "Baesa Road",
    "Caroline",
    "Commercial",
    "Dela Cruz Street",
    "Dizon Street",
    "Dominador",
    "F. Carlos Street Street",
    "F. Francisco",
    "Floresco Street",
    "Galguera Compound",
    "Gem 5 Road",
    "Gumamela",
    "Guni-guni",
    "Howmart Road",
    "Joaquin",
    "Jojo Extension",
    "Jordan Drive",
    "Kapangyarihan Compound",
    "Kulas Francisco",
    "Liwanag",
    "Lourdes",
    "Lucas R. Pascual Street",
    "Luwalhati",
    "M. Dizon Street",
    "M. Pascual Street",
    "Macabagdal Street",
    "Magsaysay",
    "Mang David Street",
    "Marangal",
    "Marikit",
    "Masagana",
    "Mendez Road",
    "Narra",
    "Oliveros Drive",
    "Osmeña",
    "Pacific",
    "Palm Road",
    "Quirino",
    "Quirino Highway",
    "Reposado",
    "Retales",
    "Reyes Compound",
    "Rivera",
    "Rivera–Apo Compound",
    "Rodriguez Drive",
    "Saint Dominic Drive",
    "Saint Loius Compound 6",
    "Saklolo",
    "Salazar Street",
    "Salvador",
    "San Francisco",
    "Santos Drive",
    "Segundo",
    "Virginia Drive"
];

export const abbeyRoad = [
    "Street",
    "Aster Street",
    "Asteroid Street",
    "Bawa Street",
    "Cactus Street",
    "Callejon-Cruz Street",
    "Camp Grezar Street",
    "Capricorn Street",
    "Del Mundo Compound",
    "Del Nacia Road",
    "Diamond Street",
    "Doña Asuncion Street",
    "Don Gregorio Street",
    "East Drive",
    "Encarnita Street",
    "F. De Los Santos",
    "F. De Los Santos Street",
    "Franco Street",
    "Gold Street",
    "Gregorio Street",
    "Gulod Road",
    "Kamabasa",
    "Katipunan Avenue",
    "Katipunan Extension",
    "King Alexander Street",
    "King Christian Street",
    "Leo Street",
    "Libra Street",
    "Linum Street",
    "Lupinus Street",
    "Magnolia Street",
    "Maligaya Street",
    "Mallow Street",
    "Manchester",
    "Marigold Street",
    "Mariposa Lily Street",
    "Mindanao Avenue",
    "Monarda Street",
    "Monico",
    "Narcissus Street",
    "North Drive",
    "Ocean Park Road",
    "Oliva de los Santos Street",
    "Palmera Street",
    "Papua Street",
    "Primula Street",
    "Quirino Highway",
    "Richland Avenue",
    "Ruben Jr. Street",
    "Ruben Sr. Street",
    "Ruben Sr. Street Extension",
    "Rugnan Circle",
    "Rugnan Street",
    "Sabila Avenue",
    "Saguitarius Street",
    "Salazar Street",
    "Sauyo Road",
    "Sipa Street",
    "Socorro Street",
    "Tanguile Street",
    "Taurus Street",
    "Urcia Street",
    "Victorino Street",
    "Virgo Street",
    "Zodiac Street"
];

export const balongBato = [
    "Bagong Lote",
    "Balonbato Foot Bridge",
    "Bayanihan",
    "Caina Drive",
    "Dinalaga Street",
    "Diversion Service Road",
    "Dose 36",
    "East Service Road",
    "Engineering",
    "English Street",
    "Flame",
    "Gladiola",
    "Ipil",
    "Language Street",
    "Leland Drive",
    "Letran",
    "Makaneneng",
    "Malolos Avenue",
    "Malolos Avenue",
    "Math Street",
    "Maximina Street",
    "MIT",
    "Muling Pagkabuhay",
    "Music Street",
    "Orchids",
    "Philippine Union College",
    "Pili Aly",
    "Pilipino Street",
    "Quirino Highway",
    "Ramelon",
    "Raminad Street",
    "Reading Street",
    "Reparo Road",
    "Rosario",
    "Saint James",
    "Saint John",
    "Saint Jude",
    "Saint Peter",
    "Saint Simon",
    "Salazar Drive",
    "Sampaguita",
    "San Beda",
    "Science Street",
    "Tangke Road",
    "Tieremas Street",
    "Victoneta Avenue",
    "West Service Road",
    "Yakal"
];

export const culiat = [
    "A. Limqueco Street",
    "Adelfa Street",
    "Admirable Lane",
    "Aldrin Street",
    "Allan Bean Street",
    "Anahaw Street",
    "Andrew Street",
    "Aquino Marquez Street",
    "Arboretum Road",
    "Armstrong Street",
    "Biker's Drive-thru",
    "Borman Street",
    "Casanova Drive",
    "Cassanova Drive Extension",
    "Cebu Extension",
    "Cenacle Drive",
    "Central Avenue",
    "Charity Lane",
    "Charles Conrad Street",
    "Charlie Conrad Street",
    "Collins Street",
    "Commonwealth Avenue",
    "Demetria Reynaldo Street",
    "Diamond Lane",
    "Emerald Lane",
    "Eugenio Compound",
    "Fisheries Street",
    "Freedom Lane",
    "Golden Lane",
    "Hizon Drive",
    "Ignacia dela Cruz Street",
    "Jasmine Street",
    "Jem 5 Street",
    "Justice Lane",
    "Kalaw Hill",
    "Las Villas Del Cielo Lane",
    "Ledesma Street",
    "Lovell Street",
    "Luciano Estrada Street",
    "Madonna Lane",
    "Magsaysay Street",
    "Maria Eva Street",
    "Maria Manguiat Street",
    "Marian Lane",
    "Mary Grace Street",
    "McDivitt Street",
    "Metro Avenue",
    "Morning Star Drive",
    "Morning Star Drive Extension",
    "Mystic Rose Drive",
    "N. Ramirez Street",
    "P. Quiambao Street",
    "Palayan Street",
    "Palmera Avenue",
    "Paz Isabel Street",
    "Peaceful Lane",
    "Prudent Lane",
    "Pura Villanueva Kalaw Street",
    "Q.C. Ville Street",
    "Renowned Lane",
    "Road 8",
    "Rufo Lane",
    "Saint Bernadette",
    "Salvador Estrada Street",
    "Salvi Street",
    "San Agustin Street",
    "San Ponciano Street",
    "Santa Felicia Street",
    "Santa Lucia Street",
    "Sunriser Street",
    "Tacloban",
    "Tagbilaran Extension",
    "Tagumpay Street",
    "Tandang Sora Avenue",
    "Tandang Sora-Commonwealth Overpass",
    "Teddy Ⅲ Street",
    "Temperance Lane",
    "Teodoro M. Kalaw Street",
    "Tyrone Street",
    "Union Drive",
    "Union Drive Extension",
    "Valerio Kalaw Street",
    "Valor Lane",
    "Vargas Lane",
    "Vicente Street",
    "Visayas Avenue",
    "Windgate Villas",
    "Z & H Street"
];

export const pasongTamo = [
    "1st Street",
    "2nd Street",
    "3rd Street",
    "4th Street",
    "5th Street",
    "7th Street",
    "8th Street",
    "Adarna Street",
    "Aguinaldo Street",
    "Akbag Street",
    "Aldrin Street",
    "Alley 2",
    "Alondras Street",
    "Amethyst Street",
    "Antonia Street",
    "APA Compound Lane",
    "Apo Street",
    "Apollo Drive",
    "AquaAramis Street",
    "ArmyAtis Street",
    "Aurelio Street",
    "Aurora Street",
    "Batangas Street",
    "Bato-bato Street",
    "Bato-bato Street Extension",
    "Bonifacio Drive",
    "Bonifacio Street",
    "Borja Street",
    "Bulacan Street",
    "C. P. Garcia Street",
    "Cadena de Amor Street",
    "Caimito Street",
    "Caldencio Street",
    "California Street",
    "Cambridge Street",
    "Camia Street",
    "Captain F. L. Facia Street",
    "Cartier Street",
    "Cattleya Street",
    "Cavite Street",
    "Cenacle Drive",
    "Central Drive",
    "Charity Street",
    "Chesnut",
    "Chicago Street",
    "Chico Street",
    "Coast Drive",
    "Coast Drive Alley",
    "Colonel S. D. Tolentino Street",
    "Columbia Street",
    "Congressional Avenue Extension",
    "Cornell Street",
    "D. Macapagal Street",
    "Dama de Noche",
    "Daniel Street",
    "Diamond Street",
    "Diego Silang Street",
    "Dinar Street",
    "Doña Regina Street",
    "Dollar Street",
    "Don Mariano Street",
    "Drakkar Street",
    "Duke Street",
    "Dumagat Street",
    "East Drive",
    "Emerald Street",
    "Emilio Street",
    "Eusebio Street",
    "Everlasting Street",
    "F. Marcos Street",
    "F. Tirona Street",
    "Faith Street",
    "Fernando Lopez Street",
    "Fernando P. Eugenio Street",
    "Ferndale SouthFernville",
    "Fidelity Street",
    "Fordham Street",
    "Fortune DriveFranc Street",
    "Francisca Tirona Benitez Street",
    "Francisco Street",
    "Freedom Street",
    "G. de Jesus Street",
    "Garnet",
    "General Luna Street",
    "General Malvar Street",
    "General Servillano Aquino Street"
];

export const sangandaan = [
    "Acuña Street",
    "AguedaAraw",
    "Banana Island",
    "Batis",
    "Bayanihan Drive",
    "Benefits Street",
    "Claims Street",
    "Cristina",
    "Dalsol",
    "Dividends",
    "Dizon",
    "Dizon Street",
    "Engineering",
    "Estrella Street",
    "G.S.I.S. Avenue",
    "Grants",
    "Insurance",
    "Insurance street",
    "Jacqueline KennedyJohn F. KennedyJojoJolo",
    "LegalLoans Street",
    "M. de Ropa",
    "M. Ramoy Compound",
    "ManagerMedical Street",
    "Mendez Road",
    "Rivera StreetPark Lane",
    "Policy Street",
    "Premium Extension",
    "Premium Street",
    "Production Street",
    "Property Street",
    "Quirino Highway",
    "Real Estate Street",
    "Redemption",
    "Retirement Road",
    "12 Extension",
    "Road 20",
    "Road 23",
    "Robert Kennedy Street",
    "Rodriguez Compound",
    "Sacred Heart",
    "Saint Benedict",
    "Saint Joseph",
    "Saint Mary",
    "Saint Michael",
    "Saint Vincent",
    "Sampalocan Street",
    "Services",
    "Short Horn Street",
    "V. Luzon Street"
];

export const santaLucia = [
    "Mabini Street",
    "Accountant",
    "Accountant Street",
    "Atherton Residences",
    "Atherton Street",
    "Baht",
    "Bukaneg Street",
    "Cambridge",
    "Chestnut",
    "Coleridge",
    "Commonwealth Avenue",
    "Contractors",
    "Cuisia Avenue",
    "Daisy Extension",
    "De Vega Compound",
    "Dirham",
    "Drachma",
    "E. Aguinaldo Street",
    "Engineer Street",
    "Engineering Street",
    "G. de Leon Street",
    "Goldstar",
    "Gotinga Drive",
    "Greenwich Street",
    "Greystone",
    "H. Ventura",
    "Hastings",
    "Homeland Street",
    "Investment",
    "Irving",
    "J. Basa Street",
    "J. P. Rizal Street",
    "Kent Street",
    "Kingfisher",
    "La Verna Street",
    "Lakandula Street",
    "Loans Lopez",
    "Lopez Jaena Street",
    "M. Aquino Street",
    "Maple",
    "Maple Street",
    "Medical",
    "Medicare",
    "Milenyo",
    "N. Ponce Street",
    "Nathan Road",
    "Oak Street",
    "Oakville",
    "Pension",
    "Percentage",
    "Personnel",
    "Personnel Extension",
    "Perugia Street",
    "Peso",
    "Pinesville",
    "Pitimini Street",
    "Pound",
    "R. Humabon Street",
    "Rand",
    "Regalado Highway",
    "Rhombus Street",
    "S. Francisco Street",
    "Salvador Street",
    "Santos",
    "Seagull",
    "ShekelSomerset Street",
    "Teachers",
    "Teachers Street",
    "Trapezoid Street",
    "Treasury",
    "VATVisayas Street",
    "Walnut",
    "Westcherster",
    "Windsor",
    "Won",
    "Woodpecker",
    "Zamora Street"
];

export const sauyo = [
    "1st Laguna Street",
    "2nd Laguna Street",
    "Abbey Road",
    "Acacia Street",
    "Ad Valorem",
    "Aganan Street",
    "AgnoAgos Lane",
    "Agusan Street",
    "Algebra",
    "Alimango Street",
    "Allah",
    "Almagica Street",
    "Angat",
    "Annalisa Street",
    "Aplaya",
    "Apo",
    "2nd Street",
    "Aries Street",
    "Arsenio Street",
    "Aster",
    "Astoria",
    "Barit Extension",
    "Barit Street",
    "Bataan Street",
    "Bawa Street",
    "Beethoven Street",
    "Biya Street",
    "Blue sky",
    "Bluebird Street",
    "Bougainvilla Street",
    "Bucao Street",
    "C. Francisco Street",
    "Calaca Street",
    "Calla Street",
    "Camia Street",
    "Camiling",
    "Candido Street",
    "Capital Gain",
    "Capizan Street",
    "Capricorn Street",
    "Carnation Street",
    "Castle Street",
    "Cedar Street",
    "Celosia Street",
    "Champaca Street",
    "Charleville",
    "Chestnut Street",
    "Chico",
    "Chopin Street",
    "Clifton Street",
    "Cotabato Street",
    "Crocus Street",
    "Cura Lane",
    "Cypress Street",
    "D. Muñoz Street",
    "Daffodils",
    "Dahlia Avenue",
    "Dahlia Extension",
    "Daisy Street",
    "Dalag Street",
    "Dao Street",
    "De Vega Compound",
    "Depot Street",
    "Derby",
    "Dinar Street",
    "Doña Angeling Street",
    "Doña Asuncion Street",
    "Doña Consuelo Street",
    "Doña Fildela Street",
    "Doña Juana Street",
    "Doña Juana Street Extension",
    "Doña Sabrina Street",
    "Doña Segundo Street",
    "Doña Teresa Street",
    "Dollar Street",
    "Dolores Street",
    "Don Jose Street",
    "Don Julio Gregorio Avenue",
    "Don Julio Gregorio Street",
    "Don Raymundo Street",
    "Don T. Lectura Street",
    "Don Vicente Street",
    "Donors",
    "El Capitan Street",
    "Elm",
    "Emerald Street",
    "Erwin Street",
    "Excise",
    "F. del Mundo Street",
    "Fercon Street",
    "Fercon Street",
    "Florville Street",
    "Florville Street Extension",
    "Fordham",
    "Franchise",
    "Franco Street",
    "Fuschia Street",
    "Galatian Street",
    "Garland Street",
    "Genesis Street",
    "Geometry",
    "Georgia",
    "Ghana",
    "Glenmont Circle",
    "Gold Street",
    "Greece",
    "Greenland Street",
    "Greenlane",
    "Greenview Avenue",
    "Greenview Avenue",
    "Greenville Drive",
    "Greg Street",
    "Grenada",
    "Guadeloupe",
    "Hammer Road",
    "Harlington Street",
    "Harvard",
    "Hikom Street",
    "Hito Street",
    "Ibayo Ⅱ Street",
    "Ilang-ilang Street",
    "Income",
    "Jade Street",
    "Jalaur Triangle",
    "Jamaica",
    "Jasmin Street",
    "Jean Street",
    "Jeremiah Street",
    "Kanduli Street",
    "Karen Street",
    "LawLaw Street",
    "Leo Street",
    "Liberty Street",
    "Libra Street",
    "Lilac Street",
    "Linaria Street",
    "Lionel Street",
    "Lipton Street",
    "Lobella Street",
    "Los Alamos Street",
    "Los Olivos Street",
    "Lupinus Street",
    "M. Gabriel Street",
    "MagatMagat Street",
    "Magnolia Street",
    "Main Avenue",
    "Main Street",
    "Malachi Street",
    "Malachi Street",
    "Malasila",
    "Malaya Street",
    "Maligaya Street",
    "Manchester",
    "Maranding",
    "Marbel",
    "Maria Cristina Street",
    "Marian Street",
    "Marianito Street",
    "Matimtim Street",
    "Merry",
    "Mindanao Avenue",
    "Mining",
    "Monroe Street",
    "Mozart Extension",
    "Mozart Street",
    "Mozart Street Extension",
    "MWSS Service Road",
    "Naga Street",
    "Nashville Road",
    "Naval",
    "Naval Extension",
    "New Garden",
    "Nuclear Street",
    "Old Sauyo Road",
    "Orchid Street",
    "Painty",
    "Palico Lane",
    "Pantabangan Street",
    "Paris Street",
    "Pascual Road",
    "Passiflora Street",
    "Patintero Street",
    "Pine StreetPisces Street",
    "Poinsettia Street",
    "Queensville",
    "Red Arrow",
    "Redwood",
    "Richland Drive",
    "Richland Street",
    "Richlandway",
    "Riverdale",
    "Robertson",
    "Rosal Street",
    "Roses Street",
    "Roseville",
    "Ruby Street",
    "Rugosa Street",
    "Sagittarius Street",
    "Sales",
    "Sampaguita Street",
    "Sampaloc Street",
    "Santa Barbara Street",
    "Santa Catalina Street",
    "Santa Cruz Street",
    "Santa Fe Street",
    "Santa Ines Street",
    "Santa Maria Street",
    "Santa Rita Street",
    "Santan Street",
    "Santo Domingo Street",
    "Saturnina Road",
    "Sauyo Road",
    "Science Street",
    "Siffu",
    "Sikap Lane",
    "Siklot Street",
    "Siluay",
    "Silver Street",
    "Somerset Street",
    "Sparrow Street",
    "Sugpo Street",
    "Sunflower",
    "Sunog Baga",
    "Swallow Drive",
    "Swallow Drive",
    "Tañada Street",
    "TanjayTaurus Street",
    "Taurus Street",
    "Tavern Street",
    "Topaz Street",
    "Upper Banlat Street",
    "Valeriana Compound",
    "Venus Road",
    "Verbena Street",
    "Victoria Street",
    "Victorian Avenue",
    "Virgo Street",
    "Visayas Avenue",
    "Walnut",
    "Walnut Street",
    "Whitefield",
    "Windsor",
    "Witholding",
    "Woodside",
    "Yakal Street",
    "Yellow Street",
    "Yellowstone",
];

export const talipapaStreets = [
    "38th Street",
    "Aguila Street",
    "Algebra Street",
    "Alimasag Street",
    "Apahap Street",
    "Arty 1 Road",
    "Arty 2 Road",
    "Aurigue",
    "Ayungin Street",
    "Bangus Street",
    "Belton Drive",
    "Belton Drive",
    "Bisugo Street",
    "Branches",
    "Branches Avenue",
    "C. Francisco Street",
    "Cadaing Street",
    "Camia Street",
    "Campo 1",
    "Campo 2",
    "Carnation Street",
    "Carreon Jt Drive",
    "Champaca Street",
    "Dama de Noche Street",
    "Del Mundo Street",
    "Del Nacia Drive",
    "Dela Cruz Street",
    "Diamond",
    "Don Raymundo Street",
    "G. Del Mundo Drive",
    "Galguerra Drive",
    "J. P. Ramoy Street",
    "J. P. Ramoy Street",
    "Kalapati Street",
    "Karpa Street",
    "Katipunan Avenue",
    "King's Road",
    "Kitang Street",
    "Libra Street",
    "Llano Street",
    "M. Dela Cruz Street",
    "Magnolia Place Drive",
    "Magnolia Street",
    "Makaya Street",
    "Marcel Drive",
    "Mayor Adelina Rodriguez Avenue",
    "Mindanao Avenue",
    "Mindanao Avenue",
    "Mindanao Avenue",
    "Mindanao Avenue",
    "MRC Street",
    "Old Sauyo Road",
    "Oliva de los Santos Street",
    "P. Rivera Street",
    "Pearl",
    "Piko Street",
    "Pipit Street",
    "Pugo Street",
    "Queens Road",
    "Quirino Highway",
    "Ramos Street",
    "Rolex",
    "Rook's Road",
    "Rosal Street",
    "Rufina Street",
    "Sagittarius Street",
    "Saint Andrew Street",
    "Saint Anthony Street",
    "Saint Charbel Street",
    "Saint Charles Street",
    "Saint Frances Street",
    "Saint Gregory Street",
    "Saint James Street",
    "Saint Joseph Street",
    "Saint Louis Street",
    "Saint Michael Street",
    "Saint Simon Street",
    "San Leon Street",
    "San Lorenzo Ruiz Street",
    "San Sebastian Street",
    "Santa Sabina Street",
    "Sapsap Street",
    "Siklot Street",
    "Sipa Street",
    "Sungka Street",
    "T. H. Dela Cruz Street",
    "Tamban Street",
    "Tandang Sora Avenue",
    "Tandang Sora Avenue Extension",
    "The Junction Place Road",
    "Virgo Street",
    "Waling-waling Street"
];

export const tandangSoraStreets = [
    "1st Laguna Street",
    "2.91KM",
    "2nd Laguna Street",
    "Acuna Dr",
    "Aganat St",
    "Agno St",
    "Agusan St",
    "Alcantara St",
    "Allah St",
    "Allajur St",
    "Ambuklao St",
    "Angat St",
    "Aplaya St",
    "Aries St",
    "Arimado St",
    "Auditing",
    "Australia St",
    "Bagatua Compound",
    "Banlat Rd",
    "Banlat St",
    "Binga St",
    "Bituin",
    "Botocan St",
    "Brillante Road",
    "Brilliante",
    "Brunei St",
    "Bulova St",
    "Calaca St",
    "Caliraya St",
    "Calle Real",
    "Camelia St",
    "Camiling St",
    "Capricorn St",
    "Carnation St",
    "Caroline St",
    "Cattleya",
    "Chico Dr",
    "College Dr",
    "Cometa",
    "Cornus St",
    "Creekside De",
    "Cucurbeta St",
    "D. Munoz Avenue",
    "Daffodil",
    "Daisy",
    "Dao",
    "Daylily",
    "De Jesus St",
    "Denmark St",
    "Diamond",
    "Diamond St",
    "Dimasalang",
    "Dinar St",
    "Dingle St",
    "Don Felipe Street",
    "Don Jose St",
    "Dona Sotera St",
    "Edward St",
    "Elias St",
    "Emerald St",
    "Escarlata",
    "Esmeralda Rd",
    "Evergreen St",
    "Fercon Street",
    "Fern",
    "Florencio Lerma",
    "Florville Extension",
    "Florville Street",
    "Franc St",
    "Garcia St",
    "Gen. Fullon",
    "Gen. M. Hizon",
    "Gen. Torres St",
    "General Ave",
    "General Martin",
    "General Santos ST",
    "Gloria Ave",
    "Gold Street",
    "Golden Street",
    "Green Fields St",
    "Green Forest St",
    "Green Grass St",
    "Green Ln",
    "Green Ln St",
    "Green Plain St",
    "Green Valley St",
    "Greenhills St",
    "Greenleaves",
    "Greenview Ave",
    "Grem",
    "GSISEA St",
    "Guevarra St",
    "Himlayan Road",
    "Investment",
    "Ipil",
    "Ivory Street",
    "Jacqueline St",
    "Jade",
    "Jade St",
    "Jocson St",
    "John St",
    "Jovan St",
    "Kalayaan St",
    "Kennedy Dr",
    "Landcom E",
    "Landcom S",
    "Landcom W",
    "Lazaro",
    "Leo St",
    "Libra St",
    "Loboc St",
    "Longines St",
    "M. Aquino St",
    "Macban St",
    "Magat St",
    "Magdalo",
    "Magdiwang",
    "Malaya St",
    "Maranding",
    "Marbel Rd",
    "Maria Christina St",
    "Mars St",
    "Matville",
    "Mayor Adelina Rodriguez",
    "Melguas",
    "Mercury St",
    "Metropolitan St",
    "Molave",
    "Naga St",
    "Narra",
    "Neptune St",
    "North Rd",
    "Orchids",
    "Palimpinon St",
    "Palm",
    "Pangilinan St",
    "Pantabangan St",
    "Patrick St",
    "Pearl",
    "Peso St",
    "Platinum St",
    "Reynaldo",
    "Rolex St",
    "Roque Dr",
    "Rosal",
    "Ruby",
    "Rugnan St",
    "Sagittarius St",
    "Saint Martin",
    "San Andres St",
    "San Beta Rd",
    "San Felipe St",
    "San Isidro",
    "San Marcelino",
    "San Martin",
    "San Narciso",
    "Sapphire St",
    "Sarmiento St",
    "Saturnina St",
    "Sevilla Street",
    "Siffu St",
    "Siluay St",
    "Silver St",
    "ST Bernard",
    "St Charbel St",
    "St Charles",
    "St Gabriel",
    "St Gregory",
    "St Joseph",
    "St Joseph Townhomes Rd",
    "St Jude",
    "St Matthew St",
    "St Michael St",
    "St Simon St",
    "Sterling St",
    "Sunshine",
    "Tala",
    "Tanada St",
    "Tandang Sora Ave",
    "Taurus St",
    "Teotimo",
    "Tiwi St",
    "Tongonan St",
    "Torres Dr",
    "University Ln",
    "Upper Banlat St",
    "Venus Rd",
    "Venus St",
    "White",
    "William St",
    "William St Ext",
    "Yellow Street"
];